### PR TITLE
*API KEY IS IN THE TRELLO* *ADD ENV FILE AND PASTE

### PR DESCRIPTION
**Pull request by TyJHennig**

### CODE REVIEW

**Comment by TyJHennig** [comment]
CLOUDINARY_URL=cloudinary://978957791656336:AJ0Gz1hddnHU-bw9RuV6piivqeQ@doizo65a2

**Comment by TyJHennig** [comment]
> CLOUDINARY_URL=cloudinary://978957791656336:AJ0Gz1hddnHU-bw9RuV6piivqeQ@doizo65a2

Make an ENV file and paste this in 

touch .env
echo '.env*' >> .gitignore

**Review by jess-nash — APPROVED** [review]
LGTM

**Review by k-ashmore — DISMISSED** [review]
lgtm

**Review by k-ashmore — APPROVED** [review]
Now looks dope

**Pull request merged**
