### PR TITLE
created item model

### PR DESCRIPTION
**Pull request by TyJHennig**
Made the item model

### CODE REVIEW

**Review by jess-nash — APPROVED** [review]
LGTM! 
(looks good to me)

**Comment by rkam808** [comment]
@TyJHennig Jessica had to re-create the User model using devise, so you will have to make some changes before this PR can get merged.
Reviewers: DO NOT MERGE until Jessica's new PR for creating User model with devise is merged with master.

**Review by noliver-ykc — COMMENTED** [review]
LGTM

**Review by noliver-ykc — APPROVED** [review]

**Review by k-ashmore — APPROVED** [review]
LGTM

**Pull request merged**
