### PR TITLE
added mini category cards to use on homepage later on

### PR DESCRIPTION
**Pull request by noliver-ykc**
not important right now so feel free to push this later

### CODE REVIEW

**Review by jess-nash — CHANGES_REQUESTED** [review]
I think it looks snazy, but I think the category html in the home page should be rendered into that page from a shared file.

**Comment by noliver-ykc** [comment]
> I think it looks snazy, but I think the category html in the home page should be rendered into that page from a shared file.

fixed it

**Review by k-ashmore — APPROVED** [review]
LGTM

**Review by jess-nash — APPROVED** [review]
LGTM

**Pull request merged**
