### PR TITLE
Changed new item form to simple form

### PR DESCRIPTION
**Pull request by k-ashmore**

### CODE REVIEW

**Review by noliver-ykc — APPROVED** [review]
LGTM

**Review by jess-nash — COMMENTED** [review]
Looks good
Just one small thing I'd like to get changed is the category collection
I think those are what I original put in cause I didn't know what categories we were going to go with.

In the seeds, we have "equipment" and "instrument" and then also maybe "music tech" ?

**Review by TyJHennig — CHANGES_REQUESTED** [review]
Yeah I agree that we should settle category in a strict sense now before we go further so that we're not back tracking later to fix it before Sat.

**Comment by noliver-ykc** [comment]
whatever we change it to, remember to change the list in the search bar too (green side)

**Comment by k-ashmore** [comment]
Looking at Sam Ash and Sweetwater (big music stores in US) and they have some categories. We can combine guitars, drums etc. into "instruments". Maybe "recording" and "DJ gear" as two others could be good.

**Sweetwater**
sweetwater
**Sam Ash**
samash

**Comment by TyJHennig** [comment]
HERE IS ONE SUGGESTION: 
Lets add/ remove as a group to nail down what we can all agree upon.
Comment below what you think needs to be added or deleted.

- One category for instruments 
- recording equipment 
- DJ gear 
- Sound (amps, mics, soundboards, speakers)

**Comment by k-ashmore** [comment]
Final 4:
- Instruments
- Recording equipment
- DJ gear
- Amps

**Review by TyJHennig — APPROVED** [review]

**Review by jess-nash — APPROVED** [review]
LGTM

**Pull request merged**
